// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApiDeloitte.Model.DBContext;

namespace WebApiDeloitte.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20221113214704_DBInit")]
    partial class DBInit
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("WebApiDeloitte.Model.Bulletin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("Int")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DeliveryDate")
                        .HasColumnType("dateTime");

                    b.Property<int>("IdStudenty")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK_Bulletins");

                    b.ToTable("Bulletins");
                });

            modelBuilder.Entity("WebApiDeloitte.Model.BulletinGrade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("Int")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Grade")
                        .HasColumnType("int");

                    b.Property<int>("IdBulletin")
                        .HasColumnType("int");

                    b.Property<int>("IdDiscipline")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK_BulletionGrades");

                    b.ToTable("BulletinGrade");
                });

            modelBuilder.Entity("WebApiDeloitte.Model.Discipline", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("Int")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Workload")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK_Disciplines");

                    b.ToTable("Discipline");
                });

            modelBuilder.Entity("WebApiDeloitte.Model.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("Int")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("dateTime");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK_Students");

                    b.ToTable("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
